name: Play Chess Workflow

on:
  issues:
    types:
      - opened
  issue_comment:
    types:
      - created

jobs:
  play-chess:
    runs-on: ubuntu-latest
    steps:
      - name: Use Play Chess Action
        uses: rudra-iitm/chess-actions@main
        with:
          issue_number: ${{ github.event.issue.number }}
          repository_owner: ${{ github.repository_owner }}
          repository_name: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
